[versions]
kotlin = "2.0.0"

[libraries]
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version = "5.1.0" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
sonarqube = { id = "org.sonarqube", version = "5.0.0.4638" }
jreleaser = { id = "org.jreleaser", version = "1.12.0" }