[versions]
kotlin = "2.0.20"

[libraries]
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version = "5.11.0" }
classgraph = { module = "io.github.classgraph:classgraph", version = "4.8.174" }
okio = { module = "com.squareup.okio:okio", version = "3.9.0" }
assertj-core = { module = "org.assertj:assertj-core", version = "3.26.3" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
sonarqube = { id = "org.sonarqube", version = "5.1.0.4882" }
jreleaser = { id = "org.jreleaser", version = "1.13.1" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
android-library = { id = "com.android.library", version = "8.5.2" }